name: Run Pytest on Push

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Run tests when pushing to main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to main

jobs:
  test:
    runs-on: ubuntu-latest  # Run on a Linux machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Clones your code

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Adjust to your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install pytest

      - name: Run Tests
        run: pytest  # Execute pytest
